# Generated by Django 5.0.4 on 2024-12-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyDetails',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('lab_name', models.CharField(max_length=100)),
                ('lab_id', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='faculty_images/')),
            ],
            options={
                'db_table': 'facultydetails',
            },
        ),
        migrations.CreateModel(
            name='LabDetails',
            fields=[
                ('lab_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('lab_name', models.CharField(max_length=100)),
                ('faculty_in_charge', models.CharField(max_length=100)),
                ('faculty_incharge_id', models.CharField(max_length=15)),
                ('lab_count', models.IntegerField(default=0)),
                ('lab_description', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'labdetails',
            },
        ),
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('lab_name', models.CharField(max_length=100)),
                ('lab_id', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='student_images/')),
            ],
            options={
                'db_table': 'studentdetails',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_faculty', models.BooleanField(default=False)),
                ('is_student', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
    ]
