# Generated by Django 5.0.4 on 2024-12-26 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultydetails',
            name='user',
            field=models.ForeignKey(db_column='user_id', default=0, on_delete=django.db.models.deletion.CASCADE, to='loginapp.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='user',
            field=models.ForeignKey(db_column='user_id', default=0, on_delete=django.db.models.deletion.CASCADE, to='loginapp.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facultydetails',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
